name: flutter_starter
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # ui
  lucide_icons: ^0.257.0
  gap: ^3.0.1

  # utils
  go_router: ^13.2.0
  easy_localization: ^3.0.4
  envied: ^0.5.3
  logger: ^2.1.0
  uuid: ^4.3.3

  # state management
  riverpod_annotation: ^2.3.4
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10

  # backend
  supabase_flutter: ^2.3.4

  # annotation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # linting
  flutter_lints: ^3.0.0
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9

  # code gen
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  envied_generator: ^0.5.3
  freezed: ^2.4.7
  json_serializable: ^6.7.1

  # utils
  import_sorter: ^4.6.0
  
flutter:

  uses-material-design: true

  assets:
    - assets/translations/